In [10]:
import numpy as np

In [11]:
a1 = np.array(['a','b','c','d','e','f','g','h','i','j'])

In [12]:
a1.shape

(10,)

In [13]:
a1.dtype

dtype('<U1')

In [14]:
a1.size

10

In [25]:
a2 = np.arange(2,33,2).reshape(4,4)

In [26]:
a2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [42]:
a3 = np.linspace(2,32,16).reshape(4,4)

In [43]:
a3

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [51]:
a4 = np.arange(1,26).reshape(5,5)

In [48]:
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
a4[a4 % 2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])